// Constant will define here.
export const DISMISS_ITEM_RECOMMEND = 'DISMISS_ITEM_RECOMMEND';
export const INCREASE_FOLLOWING = 'INCREASE_FOLLOWING';
export const CHANGE_DETAIL = 'CHANGE_DETAIL';
export const CHANGE_AUTH_TAB = 'CHANGE_AUTH_TAB';