// Constant will define here.
export const DISMISS_ITEM_RECOMMEND = 'DISMISS_ITEM_RECOMMEND';
export const INCREASE_FOLLOWING = 'INCREASE_FOLLOWING';
export const UPDATE_DETAIL = 'UPDATE_DETAIL';
export const CHANGE_AUTH_TAB = 'CHANGE_AUTH_TAB';
export const CHANGE_ACCOUNT_INFO = 'CHANGE_ACCOUNT_INFO';
export const CHANGE_USER_INFO = 'CHANGE_USER_INFO';
